<?php

namespace Plugin\ALIJSettlementIV\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\ALIJSettlementIV\Entity\Config;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * ConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Config::class);
    }

    public function get()
    {
        return $this->findOneBy(array());
    }
}
